
# REQUIRED
plex_url: ''
plex_owner_name: '' # To include owner in groups
plex_owner_token: ''
plex_client_identifier: '' # See README on how to obtain
# REQUIRED END

# RUN SETTINGS
# WARNING: Full runs can take a while to complete
dry_run: True # Do a test run without updating. Useful to test filters before commiting
full_run_on_start: False # Update every item in all libraries using the filters when the applicacation is ran. Recommended to only run ONCE and set up a webhook for new media
full_run_cron_expression: '' # To do a full run at an interval or time of day. See: https://crontab.guru/
# RUN SETTINGS END

# BATCH SETTINGS
# WARNING: Changing these values can cause unexpected errors. Increase batch_size and reduce batch_delay to speed up but use more CPU
# Processing streams
process_batch_size: 5
process_batch_delay: 500
# Updating users
update_batch_size: 50
update_batch_delay: 100
# BATCH SETTINGS END

# GROUPS
# List usernames EXACTLY like they appear in Plex. Include capital letters and special characters
# Optionally use $ALL in place of username to include ALL users from your server
groups:
  serialTranscoders: # Can be named anything
    - varthe
    - UserWithCapitalLetters # EXACTLY like in plex INCLUDING capital letters.
    # - $ALL
  subtitleEnjoyers: # Can be named anything
    - user1
    - user2
  deafPeople: # Can be named anything
    - user2
    - user3
  weebs: # Can be named anything
    - user3
    - user4
# GROUPS END

# FILTERS
filters:
  Movies: # Library name
    serialTranscoders: # Group name
      audio:
        # Audio Filter 1 - First English audio track that's not TRUEHD and not a commentary
        - include:
            language: English
          exclude:
            codec: truehd
            extendedDisplayTitle: commentary # Checks whether the word "commentary" is present
        # Audio Filter 2 - Any English track (fallback if the above filter doesn't match)
        - include:
            language: English
      subtitles:
        # Subtitle Filter 1- First English track that's not forced
        - include:
            language: English
          exclude:
            extendedDisplayTitle: forced
    deafPeople: # Group name
      subtitles:
        # Subtitle Filter 1 - First English SDH track
        - include:
            language: English
            extendedDisplayTitle: sdh
  Anime: # Library name
    weebs: # Group name
      audio:
        - include:
            languageCode: jpn # Japanese
      subtitles:
        - include:
            language: English
          exclude:
            extendedDisplayTitle: signs


