# REQUIRED
plex_server_url: ""
plex_owner_name: ""  # Use this value in place of username to include the owner in groups
plex_owner_token: ""
plex_client_identifier: ""  # See README on how to obtain
# REQUIRED END

# RUN SETTINGS
dry_run: True  # For testing filters; won't update users. Recommended to test a few times to ensure filters work.

# PARTIAL RUN: Updates newly added media since the last run.
# WARNING: The first run will update all existing media. Subsequent runs will be faster.
partial_run_on_start: False
partial_run_cron_expression: ""  # E.g., '0 3 * * *' to run every day at 3:00 am. See crontab.guru
# RUN SETTINGS END

# GROUPS
groups:
  serialTranscoders:
    - varthe
    - UserWithCapitalLetters
    - $ALL # Will grab all users with access to the library
  subtitleEnjoyers:
    - varthe
  deafPeople:
    - varthe
  weebs:
    - varthe
    - user4
# GROUPS END

# FILTERS - See README for explanation
filters:
  Movies:
    serialTranscoders:
      audio:
        - include:
            language: English
          exclude:
            codec: truehd
            extendedDisplayTitle: commentary
        - include:
            language: English
    subtitleEnjoyers:
      subtitles:
        - include:
            language: English
          exclude:
            extendedDisplayTitle: forced
    deafPeople:
      subtitles:
        - include:
            language: English
            extendedDisplayTitle: sdh
  Anime:
    weebs:
      audio:
        - include:
            languageCode: jpn  # Japanese
      subtitles:
        - include:
            language: English
            extendedDisplayTitle: full
        - include:
            language: English
            extendedDisplayTitle: dialogue
        - include:
            language: English
          exclude:
            extendedDisplayTitle: signs
