# REQUIRED
plex_server_url: ""
plex_owner_name: "" # Use this value in place of username to include the owner in groups
plex_owner_token: ""
plex_client_identifier: "" # See README on how to obtain
# REQUIRED END

# RUN SETTINGS
dry_run: True # For testing filters; won't update users. Recommended to test a few times to ensure filters work.

# PARTIAL RUN: Updates newly added media since the last run.
# WARNING: The first run will update all existing media. Subsequent runs will be faster.
partial_run_on_start: False
partial_run_cron_expression: "" # E.g., '0 3 * * *' to run every day at 3:00 am. See crontab.guru
# CLEAN RUN: Updates all existing media. Should only be used if you want to re-apply a new set of filters on your libraries.
clean_run_on_start: False
skipInaccessibleItems: False # Skip updates that return HTTP 403 because the user cannot access the item
# RUN SETTINGS END

# MANAGED ACCOUNTS (optional)
# managed_users:
#   user1: token
#   user2: token
# MANAGED USERS END

# GROUPS
groups:
  serialTranscoders:
    - varthe
    - UserWithCapitalLetters
    - $ALL # Will grab all users with access to the library
  subtitleEnjoyers:
    - varthe
  deafPeople:
    - varthe
  weebs:
    - varthe
    - user4
# GROUPS END

# FILTERS - See README for explanation
filters:
  Movies:
    serialTranscoders:
      audio:
        # Audio Filter 1 - First English audio track that's not TRUEHD/DTS and not a commentary
        - include:
            language: English # Needs to be in the original language, e.g Español for Spanish
            # languageCode: eng # Alternative to the above, e.g. jpn for Japanese
          exclude:
            codec:
              - truehd
              - dts
            extendedDisplayTitle: commentary
        # Audio Filter 2 - Any English track (fallback if the above filter doesn't match)
        - include:
            language: English
    subtitleEnjoyers:
      subtitles:
        - include:
            language: English
          exclude:
            extendedDisplayTitle: forced
    deafPeople:
      subtitles:
        - include:
            extendedDisplayTitle: sdh
  Anime:
    weebs:
      audio:
        - include:
            language: English
          on_match:
            subtitles: disabled
        - include:
            languageCode: jpn # Japenese
          on_match:
            subtitles:
              - include:
                  language: English
                  extendedDisplayTitle: full
              - include:
                  language: English
                  extendedDisplayTitle: dialogue
              - include:
                  language: English
                exclude:
                  extendedDisplayTitle: signs
