name: Publish image to Docker Hub
on:
  release:
    types: [published]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t varthe/defaulterr:latest
      - name: publish
        run: |
          docker login -u varthe -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push varthe/defaulterr:latest